a=[]
a1=input("enter fruits name: ")
a.append(a1)
a2=input("enter fruits name: ")
a.append(a2)
a3=input("enter fruits name: ")
a.append(a3)
a4=input("enter fruits name: ")
a.append(a4)
a5=input("enter fruits name: ")
a.append(a5)
a6=input("enter fruits name: ")
a.append(a6)
a7=input("enter fruits name: ")
a.append(a7)
print(a)